spring.application.name=demo

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/lab8demo
spring.datasource.username=postgres
spring.datasource.password=Fayq592

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect